FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN echo "America/New_York" > /etc/timezone

# folder in docker container used for the files copied
WORKDIR /code/

# copy the files to WORKDIR
COPY ./*.* ./

EXPOSE 11434 4000

RUN /code/ollallm-setup-docker.sh 





