FROM ankane/pgvector

# environment variables are set on build-docker-images.sh

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN echo "America/New_York" > /etc/timezone

# folder in docker container used for the files copied
WORKDIR /code

# copy the files to WORKDIR
COPY ./*.* ./

EXPOSE 5432

RUN /code/postgres-setup-docker.sh 





