FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN echo "America/New_York" > /etc/timezone

# setting up os env, APPDIR is set in conf/config
USER root
WORKDIR /home/nonroot/code
RUN groupadd -r nonroot && useradd -r -g nonroot -d /home/nonroot/code -s /bin/bash nonroot

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# setting up python3
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y build-essential software-properties-common curl sudo wget git
RUN apt-get install -y python3 python3-pip python3-venv

COPY . /home/nonroot/code/.
# There is a volumn mounted at the docker :/code
# the docker-compose.yml has a volume :/code for this whole folder

#loading config values
RUN . conf/config
# check environment variables
RUN printenv > environment.txt
EXPOSE 11434 4000

RUN bin/ollallm-setup-docker.sh

# start processing as nonroot user
RUN chown -R nonroot:nonroot /home/nonroot/code

USER nonroot

# this is better than RUN, it tells docker that it is the last step
# otherwise docker is looping for another step
ENTRYPOINT [ "/bin/bash", "bin/ollallm-start-docker-programs.sh"]








