#!/bin/bash

# This script sets up the Conda environment for the AI Database Chatbot project.
# It checks for the existence of a .env file, loads environment variables from it,
# and ensures the specified Conda environment is activated.
#
# Parameters:
#   None
#
# Environment Variables:
#   - CONDA_PREFIX: If set, the script assumes the Conda environment is already activated.
#
# Behavior:
#   - If the .env file does not exist, the script prints an error message and exits.
#   - The script loads environment variables from the .env file.
#   - It checks if the specified Conda environment exists and creates it if necessary.
#   - If the Conda environment is not activated, the script activates it.
#
# Usage:
#   source setup_conda
#
# Dependencies:
#   - Conda must be installed and accessible in the system's PATH.
#   - The .env file must be present in the project directory.
#   - The conda_config.yaml file must be present in the project directory and contain the name of the Conda environment.
#
# Returns:
#   - 0 if the Conda environment is successfully activated or already activated.
#   - 1 if the .env file is not found.
#


# Check if .env file exists
if [ ! -f .env ]; then
  echo "Error: .env file not found."
  echo "Please, create a .env file. Instructions can be found in the README.md file."
  return 1
fi

# Load the environment variables
source .env

# get enviroment name from the conda_config.yaml file
yaml_file_path="./conda_config.yaml"
enviro=$(grep 'name:' "$yaml_file_path" | awk '{print $2}')

# Check if the environment exists
if ! conda env list | grep -q "$enviro"; then
  echo "Creating a new conda environment named $enviro..."
  # Create a new conda environment named "$enviro" using the configuration file "conda_config.yaml"
  conda env create -f conda_config.yaml
fi

# Check if CONDA_PREFIX is set
if [ -z "$CONDA_PREFIX" ]; then
  conda activate "$enviro"
fi

if [[ "$CONDA_DEFAULT_ENV" == "$enviro" ]]; then
  echo "The conda environment $enviro is already activated."
else
  echo "Activating the conda environment $enviro..."
  conda activate "$enviro"
fi


